version: '3.4'
services:
  app:
    image: vasuadari/hello-world:elixir
    environment:
      - MIX_ENV
      - VIRTUAL_HOST
    expose:
      - 4000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - nginxdata:/etc/nginx
    ports:
      - 80:80

  nginx_conf_generator:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/templates/:/etc/docker-gen/templates
      - nginxdata:/etc/nginx

volumes:
  nginxdata:
